package com.pctb.webapp.entity;

public enum NotificationType {
    GROUP,
    GROUP_FILE,
    GROUP_MEMBER_JOINED,
    GROUP_UPLOAD_PERMISSION_GRANTED,
    GROUP_UPLOAD_PERMISSION_REVOKED,
    GROUP_FILE_UPLOADED,
    GROUP_FILE_MOVED_TO_TRASH,
    GROUP_FILE_RESTORED,
    GROUP_MEMBER_KICKED,
    GROUP_MEMBER_LEFT,
    GROUP_PASSWORD_CHANGED
}
