spring.application.name=webapp

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.data.redis.url=${RD_URL}

jwt.signerKey=${JWT_SIGNER_KEY}

server.servlet.context-path=/api/v1

# Hiển thị các câu lệnh SQL (INSERT, UPDATE...) lên màn hình console để dễ tìm lỗi
spring.jpa.show-sql=true

# Định dạng câu lệnh SQL in ra cho đẹp và dễ đọc
spring.jpa.properties.hibernate.format_sql=true

# BÁU VẬT CỦA JPA: Tự động quản lý bảng
spring.jpa.hibernate.ddl-auto= update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${APP_USERNAME}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP sống được 5 phút
app.otp.ttl-seconds=300
# Sau 60 giây mới được gửi lại
app.otp.resend-cooldown-seconds=60
# Mỗi email gửi tối đa 5 lần / ngày
app.otp.max-send-per-day=5
# Bộ đếm limit reset // tức là sau 24h sẽ xóa số lần gửi tối đa dưới redis
app.otp.limit-ttl-seconds=86400

app.admin.username=${ADMIN_USERNAME}
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.fullname=${ADMIN_FULLNAME}






