spring.application.name=webapp

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.signerKey=${JWT_SIGNER_KEY}

server.servlet.context-path=/api/v1

# Hiá»ƒn thá»‹ cÃ¡c cÃ¢u lá»‡nh SQL (INSERT, UPDATE...) lÃªn mÃ n hÃ¬nh console Ä‘á»ƒ dá»… tÃ¬m lá»—i
spring.jpa.show-sql=true

# Äá»‹nh dáº¡ng cÃ¢u lá»‡nh SQL in ra cho Ä‘áº¹p vÃ  dá»… Ä‘á»c
spring.jpa.properties.hibernate.format_sql=true

# BÃU Váº¬T Cá»¦A JPA: Tá»± Ä‘á»™ng quáº£n lÃ½ báº£ng
spring.jpa.hibernate.ddl-auto= update



jwt.accessTokenDuration=${JWT_ACCESS_TOKEN_DURATION:3600}
jwt.refreshTokenDuration=${JWT_REFRESH_TOKEN_DURATION:604800}
jwt.loginAttemptLimit=${JWT_LOGIN_ATTEMPT_LIMIT:5}
jwt.loginAttemptWindowSeconds=${JWT_LOGIN_ATTEMPT_WINDOW_SECONDS:300}

spring.data.redis.host=${RD_HOST:${RD_USERNAME:${REDISHOST:localhost}}}
spring.data.redis.port=${RD_PORT:${REDISPORT:6379}}
spring.data.redis.username=${REDISUSERNAME:default}
spring.data.redis.password=${RD_PASSWORD:${REDISPASSWORD:}}
spring.data.redis.timeout=2s
spring.data.redis.database=0

spring.security.oauth2.client.registration.google.client-id=${GG_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GG_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email,openid

